"""Shared product limits and mode names."""

MAX_COMMAND_LEN = 500
MAX_QUANTITY = 10_000

ACTIVATION_AUTO = "auto"
ACTIVATION_MOTION = "motion"
ACTIVATION_SIMULATION = "simulation"
ACTIVATION_ALWAYS_LISTEN = "always_listen"
ACTIVATION_MANUAL = "manual"

VALID_ACTIVATION_MODES = {
    ACTIVATION_AUTO,
    ACTIVATION_MOTION,
    ACTIVATION_SIMULATION,
    ACTIVATION_ALWAYS_LISTEN,
    ACTIVATION_MANUAL,
}
